# Generated by Django 5.0.7 on 2024-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_card_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
