# Generated by Django 5.0.7 on 2024-08-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='quantity',
        ),
    ]
