# Generated by Django 5.0.7 on 2024-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_remove_deckcard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
