# Generated by Django 5.0.7 on 2024-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_deckcard_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='pokedex.card'),
        ),
    ]
